name: Run tests for posmulten-hibernate4-spring-boot

on:
  push:
    paths:
    - 'posmulten-hibernate4-spring-boot/**'
    - '.github/workflows/posmulten-hibernate4-spring-boot.yml'

## The action created based on the description from https://docs.github.com/en/actions/guides/creating-postgresql-service-containers

jobs:
  build:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Prepare database
      working-directory: "posmulten-hibernate4-spring-boot/scripts"
      run:  |
        psql -f './create-database.sql' -U postgres
#        psql -f 'create-database-owner.sql' -U postgres
#        psql -f 'create-database-user.sql' -U postgres

    - name: Build with Maven
      run: cd posmulten-hibernate4-spring-boot && mvn -DskipTests clean install && mvn test && mvn -P !integration-tests,e2e-tests test